li.active{
    background-color: #007EB6;
    padding: 5px;
    padding-left: 15px;
    padding-right: 15px;
}

li{
    background-color: #1DAEEC;
    padding: 5px;
    padding-left: 15px;
    padding-right: 15px;
}

li a{
    color: #fff;
}

.breadcrumb .active a {
  color: #fff;
}

.breadcrumb > li + li::before {
  content: "";
}

.panel-default > .panel-heading {
  color: #333;
  background-color: #fff; 
  border-color: #ddd;